# Generated by Django 5.1.7 on 2025-05-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplooye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('esal', models.IntegerField()),
                ('ename', models.IntegerField(max_length=64)),
                ('eaddr', models.CharField(max_length=100)),
            ],
        ),
    ]
