# Generated by Django 5.1.7 on 2025-04-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_sal', models.IntegerField(max_length=10)),
                ('emp_addr', models.CharField(max_length=30)),
            ],
        ),
    ]
